name: Publish
  
on:
  push:
    branches:
    - main
    paths:
      - '*/Project/Sources/**/*.4dm'
      - '*/Project/Sources/*/*.4DForm'
      - '*/Project/Sources/*.4DCatalog'
      - '*/Project/Resources/**'
  workflow_dispatch:
    inputs:
        mode:
          type: choice
          description: semantic versioning
          options: 
          - patch
          - minor 
          - major
          required: true

env: 
  project_path: example/Project/example.4DProject
  
jobs:

  publish:
    runs-on: [macos-latest]
    steps:

      - name: configure
        id: configure
        run: |
          if [ ${mode} = '' ]; then
          echo "mode=patch" >> $GITHUB_OUTPUT          
          else
          echo "mode=${mode}" >> $GITHUB_OUTPUT
          fi
          echo "project_path=${GITHUB_WORKSPACE}/${project_path}" >> $GITHUB_OUTPUT 
        shell: bash
        env:
          mode: ${{ inputs.mode }} 

      - name: print result
        run: |
          echo "mode: ${mode}"
          echo: "project_path: ${project_path}"
        env: 
          mode: ${{ steps.configure.outputs.mode }}
          project_path: ${{ steps.configure.outputs.project_path }}

          
