name: Sign Component
on: 
  push:
  workflow_dispatch:
    
env:
  keychain_password: 1234

jobs:
  sign:
    runs-on: macos-latest
    steps:
    
    - name: install credentials
        env:
          APPLE_DEVELOPER_ID_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE }}
          APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ env.keychain_password }}
        run: |
          CERTIFICATE_PATH=${RUNNER_TEMP}/cer.p12
          KEYCHAIN_PATH=${RUNNER_TEMP}/app-signing.keychain-db
          echo -n "${APPLE_DEVELOPER_ID_CERTIFICATE}" | base64 --decode -o ${CERTIFICATE_PATH}
          security create-keychain -p "${KEYCHAIN_PASSWORD}" ${KEYCHAIN_PATH}
          security set-keychain-settings -lut 21600 ${KEYCHAIN_PATH}
          security unlock-keychain -p "{$KEYCHAIN_PASSWORD}" ${KEYCHAIN_PATH}
          security import ${CERTIFICATE_PATH} -P "${APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD}" -A -t cert -f pkcs12 -k ${KEYCHAIN_PATH}
          security list-keychain -d user -s ${KEYCHAIN_PATH}
