name: Sign Component

on: 
  workflow_dispatch:

env:
  build_dir: build
  product_name: example

jobs:

  sign:
    runs-on: [macos-latest]
    steps:

    - name: checkout 
      uses: actions/checkout@v4

    - name: setup
      run: |
        KEYCHAIN_PATH="${PWD}/temp.keychain-db"
        CERTIFICATE_PATH="${PWD}/Developer ID Application.p12"
        ENTITLEMENTS_PATH="${PWD}/4D.entitlements"
        echo "KEYCHAIN_PATH=${KEYCHAIN_PATH}" >> $GITHUB_ENV
        echo "CERTIFICATE_PATH=${CERTIFICATE_PATH}" >> $GITHUB_ENV        
        echo "ENTITLEMENTS_PATH=${ENTITLEMENTS_PATH}" >> $GITHUB_ENV
        echo "PRODUCT_PATH=${PWD}/${BUILD_DIR}/Components/${PRODUCT_NAME}.4dbase" >> $GITHUB_ENV
        echo "BUILD_PROJECT_PATH=${PRODUCT_NAME}/Project/${PRODUCT_NAME}.4DProject" >> $GITHUB_ENV
      env:
        BUILD_DIR: ${{ env.build_dir }}
        PRODUCT_NAME: ${{ env.product_name }}

    - name: delete keychain
      continue-on-error: true
      run: |
        security delete-keychain "${KEYCHAIN_PATH}"
      env:   
        KEYCHAIN_PATH: ${{ env.KEYCHAIN_PATH }}
    
    - name: install credentials
      continue-on-error: true
      run: |        
        echo -n "${APPLE_DEVELOPER_ID_CERTIFICATE}" | base64 --decode -o "${CERTIFICATE_PATH}"
        echo -n "${CODESIGN_ENTITLEMENTS}" | base64 --decode -o "${ENTITLEMENTS_PATH}"
        security create-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
        security set-keychain-settings -lut 21600 "${KEYCHAIN_PATH}"
        security unlock-keychain -p "{$KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
        security import "${CERTIFICATE_PATH}" -P "${APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD}" -t cert -f pkcs12 -k "${KEYCHAIN_PATH}"
        security list-keychain -d user -s "${KEYCHAIN_PATH}"
      env:
        APPLE_DEVELOPER_ID_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE }}
        APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        CODESIGN_ENTITLEMENTS: ${{ secrets.CODESIGN_ENTITLEMENTS }}
        
    - name: get tool4d
      id: get
      uses: miyako/4D/.github/actions/get-tool@v1
      with:
        platform: macos
        branch: 20.x
        version: 20.2
        build: latest
        arch: x86

    - name: build component
      id: build
      uses: miyako/4D/.github/actions/build-component@v1
      with:
        build_dir: ${{ env.build_dir }}
        build_project_path: ${{ env.BUILD_PROJECT_PATH }}
        
    - name: sign
      id: sign
      uses: miyako/4D/.github/actions/sign-app@v1
      with:
        sign: ${{ secrets.CODESIGN_APPLE_ID }} 
        keychain: ${{ env.KEYCHAIN_PATH }}
        apple_id: ${{ secrets.NOTARYTOOL_APPLE_ID }}         
        team_id: ${{ secrets.NOTARYTOOL_TEAM_ID }}   
        password: ${{ secrets.NOTARYTOOL_PASSWORD }}
        path: ${{ env.PRODUCT_PATH }}
