name: Sign Component

on: 
  workflow_dispatch:

env:
  build_dir: build
  product_name: example

jobs:

  sign:
    runs-on: [macos, self-hosted]
    steps:
    
    - name: install credentials
      continue-on-error: true
      run: |
        CERTIFICATE_PATH="${PWD}/Developer ID Application.p12"
        ENTITLEMENTS_PATH="${PWD}/4D.entitlements"
        LOG_PATH="${PWD}/SignApp.log"
        echo "CERTIFICATE_PATH=${CERTIFICATE_PATH}" >> $GITHUB_ENV        
        echo "ENTITLEMENTS_PATH=${ENTITLEMENTS_PATH}" >> $GITHUB_ENV
        echo "LOG_PATH=${LOG_PATH}" >> $GITHUB_ENV
        echo "COMPONENT_PATH=${PWD}/${BUILD_DIR}/Components/${PRODUCT_NAME}.4dbase" >> $GITHUB_ENV
        
        KEYCHAIN_PATH="${PWD}/temp.keychain-db"
        echo "KEYCHAIN_PATH=${KEYCHAIN_PATH}" >> $GITHUB_ENV
        
        echo -n "${APPLE_DEVELOPER_ID_CERTIFICATE}" | base64 --decode -o "${CERTIFICATE_PATH}"
        echo -n "${CODESIGN_ENTITLEMENTS}" | base64 --decode -o "${ENTITLEMENTS_PATH}"
        
        security create-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
        security unlock-keychain -p "{$KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
        security import "${CERTIFICATE_PATH}" -P "${APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD}" -t cert -f pkcs12 -k "${KEYCHAIN_PATH}"
        security list-keychain -d user -s "${KEYCHAIN_PATH}"
      env:
        APPLE_DEVELOPER_ID_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE }}
        APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        CODESIGN_ENTITLEMENTS: ${{ secrets.CODESIGN_ENTITLEMENTS }}
        BUILD_DIR: ${{ env.build_dir }}
        PRODUCT_NAME: ${{ env.product_name }}
        
    - name: sign
      id: sign
      uses: miyako/4D/.github/actions/sign-app@v1
      with:
        Entitlements: ${{ env.ENTITLEMENTS_PATH }} 
        nameCertificat: ${{ secrets.CODESIGN_APPLE_ID }}
        PathApp: ${{ env.ENTITLEMENTS_PATH }}       
        LogPath: ${{ env.LOG_PATH }}   
        keychain: ${{ env.COMPONENT_PATH }}

    - name: delete keychain
      run: |
        security delete-keychain "${KEYCHAIN_PATH}"
      env:   
        KEYCHAIN_PATH: ${{ env.KEYCHAIN_PATH }}
