name: Sign Component

on: 
  workflow_dispatch:

jobs:

  sign:
    runs-on: [macos, self-hosted]
    steps:
    
    - name: install credentials
      run: |
        CERTIFICATE_PATH=${RUNNER_TEMP}/cer.p12
        ENTITLEMENTS_PATH=${RUNNER_TEMP}/4D.entitlements
        LOG_PATH=${RUNNER_TEMP}/SignApp.log
        echo "CERTIFICATE_PATH=${CERTIFICATE_PATH}" >> $GITHUB_ENV        
        echo "ENTITLEMENTS_PATH=${ENTITLEMENTS_PATH}" >> $GITHUB_ENV
        echo "LOG_PATH=${LOG_PATH}" >> $GITHUB_ENV
        
        KEYCHAIN_PATH=${RUNNER_TEMP}/temp.keychain-db
        echo "KEYCHAIN_PATH=${KEYCHAIN_PATH}" >> $GITHUB_ENV
        
        echo -n "${APPLE_DEVELOPER_ID_CERTIFICATE}" | base64 --decode -o ${CERTIFICATE_PATH}
        echo -n "${CODESIGN_ENTITLEMENTS}" | base64 --decode -o ${ENTITLEMENTS_PATH}
        
        security create-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
        security set-keychain-settings -lut 21600 ${KEYCHAIN_PATH}
        security unlock-keychain -p "{$KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
        security import ${CERTIFICATE_PATH} -P "${APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD}" -A -t cert -f pkcs12 -k "${KEYCHAIN_PATH}"
        security list-keychain -d user -s ${KEYCHAIN_PATH}
      env:
        APPLE_DEVELOPER_ID_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE }}
        APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        CODESIGN_ENTITLEMENTS: ${{ secrets.CODESIGN_ENTITLEMENTS }}

    - name: checkout 
      uses: actions/checkout@v4

    - name: get tool4d
      id: get
      uses: miyako/4D/.github/actions/get-tool@v1
      with:
        platform: macos
        branch: 20.x
        version: 20.2
        build: latest
        arch: x86

    - name: build component
      id: build
      uses: miyako/4D/.github/actions/build-component@v1
      with:
        build_dir: build
        build_project_path: example/Project/example.4DProject
