name: Test - Disk Image To Zip

on: 
  workflow_dispatch:

jobs:

  test:
    runs-on: [macos-latest]
    steps:

    - name: setup 
      run: |     
        echo dmg_path="${GITHUB_WORKSPACE}/example.dmg" >> ${GITHUB_OUTPUT}
   
    - name: download dmg      
      run: |     
        curl "https://github.com/miyako/4d-template-component-cicd/releases/download/patch-0.0.2/example.dmg" -o "${dmg_path}" -sL
      env:
        dmg_path: ${{ steps.setup.output.dmg_path }}

    - name: create
      uses: miyako/4D/.github/actions/deployment-create-zip@v1
      with: 
        dmg_path: ${{ steps.setup.output.dmg_path }}

    - name: check      
      run: |     
        ls .
       
