name: Test - Get Tool Version

on: 
  workflow_dispatch:

jobs:

  test:
    runs-on: [ubuntu-latest]
    steps:
    
      - name: get values
        id: get
        uses: miyako/4D/.github/actions/get-tool@v1

      - name: print result
        run: |
          echo "platform: ${platform}"
          echo "branch: ${branch}"
          echo "version: ${version}"
          echo "build: ${build}"
          echo "arch: ${arch}"
          
        with: 
          platform: ${{ steps.get.outputs.platform }}
          branch: ${{ steps.get.outputs.branch }}
          version: ${{ steps.get.outputs.version }}
          build: ${{ steps.get.outputs.build }}
          arch: ${{ steps.get.outputs.arch }}
